### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by Merlin04** [vicr123/ts-qtplatform#1]
When I run make, I get this:
/usr/lib/x86_64-linux-gnu/qt5/bin/uic messagedialog.ui -o ui_messagedialog.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic filedialog.ui -o ui_filedialog.h
g++ -c -m64 -pipe -O2 -std=gnu++1y -Wall -W -D_REENTRANT -fPIC -DTSQTPLATFORM_LIBRARY -DQT_NO_DEBUG -DQT_X11EXTRAS_LIB -DQT_MULTIMEDIA_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtX11Extras -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtMultimedia -isystem /usr/include/x86_64-linux-gnu/qt5/QtSvg -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1/QtCore -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtConcurrent -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o platformtheme.o platformtheme.cpp
In file included from platformtheme.h:5:0,
                 from platformtheme.cpp:1:
messagedialoghelper.h:4:39: fatal error: qpa/qplatformdialoghelper.h: No such file or directory
 #include <qpa/qplatformdialoghelper.h>
                                       ^
compilation terminated.
Makefile:652: recipe for target 'platformtheme.o' failed
make: *** [platformtheme.o] Error 1

I am running Ubuntu Budgie 17.04.

**Comment by vicr123** [comment]
Try installing the package `qtbase5-private-dev` :)

**Comment by Merlin04** [comment]
Now I get:
g++ -c -m64 -pipe -O2 -std=gnu++1y -Wall -W -D_REENTRANT -fPIC -DTSQTPLATFORM_LIBRARY -DQT_NO_DEBUG -DQT_X11EXTRAS_LIB -DQT_MULTIMEDIA_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtX11Extras -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtMultimedia -isystem /usr/include/x86_64-linux-gnu/qt5/QtSvg -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1/QtCore -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtConcurrent -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o platformtheme.o platformtheme.cpp
In file included from platformtheme.cpp:1:0:
platformtheme.h:17:33: fatal error: X11/Xcursor/Xcursor.h: No such file or directory
 #include <X11/Xcursor/Xcursor.h>
                                 ^
compilation terminated.
Makefile:655: recipe for target 'platformtheme.o' failed
make: *** [platformtheme.o] Error 1

**Comment by vicr123** [comment]
`libxcursor-dev` is the package you need :)
